spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
          url: jdbc:mysql://localhost:3306/mydata?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          username: root
          password: 323900llmT
          driver-class-name: com.mysql.jdbc.Driver





#hibernate:
#  dialect: org.hibernate.dialect.MySQL5Dialect