server:

  port: 8761



eureka:

  instance:

    hostname: localhost
#    instance-id: eurekaClient
#    prefer-ip-address: true     #访问路径可以显示IP地址

  client:

    registerWithEureka: false

    fetchRegistry: false

    serviceUrl:

      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/




spring:

  application:

    name: eurka-server


