server:
  port: 8001
spring:
  application:
    name: microservicecloud-dept
eureka:
  instance:
    hostname: localhost    #hostname: eureka7001.com #eureka服务端的实例名称
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址
  client: #客户端注册进eureka服务列表内
    register-with-eureka: true #是否可检索
    fetch-remote-regions-registry: true
    serviceUrl:
      defaultZone: http://localhost:7001/eureka

       # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
info:
  app:
    name: kimi-microservicecloud
#  company:
#    name: www.kimi.com
#  build:
#    artifactId: $project.artifactId$
#    version: $project.version$